#! /bin/bash
rm -f *in *out*
echo " CSFs tests(AE) ..."
for i in CSFs
do
  echo "   Starting $i CSFs test ..."
  cp ../../templates/sample.in $i.in
  sed -i "s/XXX/density/" $i.in
  sed -i  "s/H2O-SM3/C2CAS44/" $i.in
  echo "\$qmc(vmc,move=$i,steps=100,block_len=10,discard=5,accept_ratio=0.5)" >> $i.in
  $AMOLQCRUN $i

  if [ $GEN == 1 ] ; then
       mv $i.out $i.$REF
       rm -f *.in
  else
   R=`grep "total energy" $i.$REF |awk {'print $4'}`
   C=`grep "total energy" $i.out |awk {'print $4'}`
      if [ $R == $C ] ; then
        echo -e "    $i CSFs test \e[32mpassed.\e[39m"
        rm -f $i.in $i.out
      else
        export FAILED=1
        echo -e "    $i CSFs test \e[31mfailed.\e[39m"
        echo "    Check $PWD/$i.out for more information."
      fi
   fi
done

