#! /bin/bash
rm -f *in *out*
echo " Optimization tests(AE) ..."
echo "   Checking parameter's drivatives ..."
echo ""
for i in jastrow ci mo jas+mo+ci
do
  echo "   Starting $i params driv test ..."
  cp ../../templates/drivtest.in $i.in
  sed -i "s/XXX/$i/" $i.in
  $AMOLQCRUN $i

  if [ $GEN == 1 ] ; then
       rm -f $i.out $i.in
  else
   C=`grep "passed!" $i.out | awk {'print $3'}`
      if [ "passed!" == "$C" ] ; then
        echo -e "    $i params driv test \e[32mpassed.\e[39m"
        rm -f $i.in $i.out
      else
        export FAILED=1
        echo -e "    $i params driv test \e[31mfailed.\e[39m"
        echo "    Check $PWD$i.out for more information."
      fi
   fi
done
echo ""
echo "   Optimization methods tests  ..."
echo "   Checking params optimization for jas+mo+ci"
echo "     for all opt methods exept popt(mo+ci)."

for i in varmin eminlin eminlm eminpopt
do
  echo "   Starting $i opt test ..."
  cp ../../templates/$i.in .
  $AMOLQCRUN $i


  if [ $GEN == 1 ] ; then
       mv $i.out $i.$REF
       rm -f *.in
  else

   R=`grep "total energy" $i.$REF|tail -n 1|awk {'print $4;'}`
   C=`grep "total energy" $i.out|tail -n 1|awk {'print $4;'}`
      if [ $R == $C ] ; then
        echo -e "    $i opt test \e[32mpassed.\e[39m"
        rm -f $i.in $i.out fort*
      else
        export FAILED=1
        echo -e "    $i opt test \e[31mfailed.\e[39m"
        echo "    Check $PWD/$i.out for more information."
      fi
   fi
done
