//
// Created by Michael Heuer on 15.03.18.
//

#ifndef AMOLQCPP_ATOMICNEIGHBORHOODDENSITYFUNCTION_H
#define AMOLQCPP_ATOMICNEIGHBORHOODDENSITYFUNCTION_H



#endif //AMOLQCPP_ATOMICNEIGHBORHOODDENSITYFUNCTION_H
