//
// Created by Morian Sonnet on 19.05.2017.
//

#ifndef LOCALSPINMULTIPLICITY_ELECTRONREFARRANGEMENT_H
#define LOCALSPINMULTIPLICITY_ELECTRONREFARRANGEMENT_H


class ElectronRefArrangement {
public:

private:
};


#endif //LOCALSPINMULTIPLICITY_ELECTRONREFARRANGEMENT_H
