#!/usr/bin/env zsh
#BSUB -J max-test
#BSUB -o job_j.out%J
#BSUB -W 0:30
#BSUB -M 1500
#BSUB -u christoph.schulte@rwth-aachen.de
#BSUB -N
#BSUB -n 60
#BSUB -a openmpi
#
module unload openmpi
module load openmpi/1.10.1
export AMOLQC=/home/cs846520/test/amolqc_dev_10-02-14
cd /home/cs846520/test/amolqc_dev_10-02-14/examples/MAX/STR/Ethane/with_excl/
echo ---  amolqc run with openmpi  ---
echo $LSB_MCPU_HOSTS
echo $LSB_DJOB_NUMPROC
date
$MPIEXEC --bind-to core $FLAGS_MPI_BATCH $AMOLQC/src/amolqc Ethane-max
date   
echo ---  amolqc done  ---
