
if(EXISTS $ENV{CC})
    set(CMAKE_C_COMPILER $ENV{CC})
    message("Using specified C Compiler         ${CMAKE_C_COMPILER}")
else()
    message("Using default C Compiler           ${CMAKE_C_COMPILER}")
endif()

if(EXISTS $ENV{CXX})
    set(CMAKE_CXX_COMPILER $ENV{CXX})
    message("Using specified C++ Compiler       ${CMAKE_CXX_COMPILER}")
else()
    message("Using default CXX Compiler         ${CMAKE_CXX_COMPILER}")
endif()

if(EXISTS $ENV{FC})
    set(CMAKE_Fortran_COMPILER $ENV{FC})
    message("Using specified Fortran Compiler   ${CMAKE_Fortran_COMPILER}")
else()
    message("Using default Fortran Compiler     ${CMAKE_Fortran_COMPILER}")
endif()
